-- AlterTable
ALTER TABLE `donator` MODIFY `NAME` VARCHAR(191) NULL,
    MODIFY `EMAIL` VARCHAR(191) NULL,
    MODIFY `CPF` VARCHAR(191) NULL,
    MODIFY `ID_DOA` INTEGER NULL,
    MODIFY `CELLPHONE` VARCHAR(191) NULL,
    MODIFY `UPD_AT` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `ADDRESS` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `user` MODIFY `email` VARCHAR(191) NULL,
    MODIFY `updatedAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
